//! Solid generators: extrude, revolve, sweep and loft.
//!
//! All four are the same construction: place copies of a profile's loops at successive
//! *sections* in space, skin consecutive sections with quads, and cap the ends. What
//! differs is how the sections are placed. Keeping one skinning routine means face keys,
//! orientation handling and hole handling are identical across the four features.

use std::f64::consts::TAU;

use basset_math::{ANGULAR_TOL, Frame, LINEAR_TOL, Quat, Vec2, Vec3};

use crate::csg::{BoolOp, boolean};
use crate::error::KernelError;
use crate::geometry::{
    Axis, Contour, Extent, Path3, Profile, SegmentKind, Tessellation, polygon_contains, triangulate,
};
use crate::ids::{FaceKey, FaceRole, OpId};
use crate::solid::{Face, Solid, SolidBuilder, SurfaceKind};

/// Closes a generator: heals the T-junctions its sections left and refuses to hand back a
/// shell that leaks. A profile that touches itself makes faces that cancel out, and the
/// solid that results looks right until a boolean or an export meets it; the feature that
/// asked for it should fail visibly instead.
fn seal(b: SolidBuilder) -> Result<Solid, KernelError> {
    let mut solid = b.finish();
    solid.heal();
    solid.validate()?;
    Ok(solid)
}

/// One placement of a profile: the 3D points of every loop, outer first, in the same
/// order as the profile's contours.
struct Section {
    loops: Vec<Vec<Vec3>>,
}

impl Section {
    fn place(profile: &Profile, map: impl Fn(Vec2) -> Vec3) -> Self {
        Self {
            loops: profile
                .loops()
                .map(|c| c.points.iter().map(|p| map(*p)).collect())
                .collect(),
        }
    }
}

/// Face key for the lateral face generated by one loop's curve.
fn side_key(op: OpId, seg: &crate::geometry::Segment) -> FaceKey {
    FaceKey::new(op, FaceRole::Side(seg.curve))
}

/// Skins consecutive sections. `ring` closes the last section back to the first (full
/// revolve); otherwise the ends receive caps triangulated from `profile`.
fn skin(
    b: &mut SolidBuilder,
    op: OpId,
    profile: &Profile,
    sections: &[Section],
    ring: bool,
    surface_for: impl Fn(usize, usize) -> SurfaceKind,
) -> Result<(), KernelError> {
    let pairs = if ring {
        sections.len()
    } else {
        sections.len() - 1
    };
    for s in 0..pairs {
        let (cur, next) = (&sections[s], &sections[(s + 1) % sections.len()]);
        for (l, contour) in profile.loops().enumerate() {
            let n = contour.points.len();
            for j in 0..n {
                let k = (j + 1) % n;
                let quad = [
                    cur.loops[l][j],
                    cur.loops[l][k],
                    next.loops[l][k],
                    next.loops[l][j],
                ];
                b.push_quad(side_key(op, &contour.segments[j]), surface_for(l, j), quad);
            }
        }
    }
    if !ring {
        let tris = triangulate(profile)?;
        cap(
            b,
            FaceKey::new(op, FaceRole::StartCap),
            &sections[0],
            &tris,
            false,
        );
        cap(
            b,
            FaceKey::new(op, FaceRole::EndCap),
            sections.last().unwrap(),
            &tris,
            true,
        );
    }
    Ok(())
}

/// Adds a cap. Triangles index the concatenation of the section's loops. The start cap
/// faces against the outer loop's winding normal and the end cap along it, which is the
/// orientation that agrees with the side quads whichever way the sections advance.
fn cap(b: &mut SolidBuilder, key: FaceKey, section: &Section, tris: &[[usize; 3]], along: bool) {
    let all: Vec<Vec3> = section.loops.iter().flatten().copied().collect();
    let loop_normal = crate::solid::newell_normal(&section.loops[0]);
    let desired = if along { loop_normal } else { -loop_normal };
    let surface = SurfaceKind::Planar {
        normal: desired.normalize_or_zero(),
    };
    for [i, j, k] in tris {
        let (p, q, r) = (all[*i], all[*j], all[*k]);
        let n = (q - p).cross(r - p);
        if n.dot(desired) >= 0.0 {
            b.push(key, surface, vec![p, q, r]);
        } else {
            b.push(key, surface, vec![p, r, q]);
        }
    }
}

/// Pushes the profile along its plane normal.
pub fn extrude(op: OpId, profile: &Profile, extent: Extent) -> Result<Solid, KernelError> {
    let profile = profile.normalised()?;
    let (lo, hi) = extent.range()?;
    let frame = profile.frame;
    let sections = [lo, hi].map(|d| Section::place(&profile, |p| frame.to_world(p) + frame.z * d));
    let mut b = SolidBuilder::default();
    let contours: Vec<&Contour> = profile.loops().collect();
    skin(
        &mut b,
        op,
        &profile,
        &sections,
        false,
        |l, j| match contours[l].segments[j].kind {
            SegmentKind::Line => {
                let (p, q) = (
                    contours[l].points[j],
                    contours[l].points[(j + 1) % contours[l].points.len()],
                );
                let along = frame.to_world_dir(q - p);
                SurfaceKind::Planar {
                    normal: along.cross(frame.z).normalize_or_zero(),
                }
            }
            SegmentKind::Arc { center, radius, .. } => SurfaceKind::Cylindrical {
                origin: frame.to_world(center),
                axis: frame.z,
                radius,
            },
        },
    )?;
    seal(b)
}

/// Sub-operation bit marking the scaffolding `extrude_to_face` trims a tilted extrusion
/// with. The trimmed end inherits the scaffolding's cap key, so the bit keeps it from
/// colliding with any face another region of the same feature produces, while staying a
/// deterministic function of the feature's inputs — which is what downstream references
/// need to survive edits.
const TRIM_SUB: u32 = 1 << 31;

/// Pushes the profile along its plane normal exactly up to `target`, a face of another
/// solid — Fusion's "to object" extent.
///
/// A planar target is treated as its infinite plane, as Fusion's "extend face" does, so
/// the profile does not have to sit underneath the face itself. When that plane is
/// parallel to the profile's the reach is one number and a plain extrude lands on it;
/// when it is tilted the extrusion is pushed past the farthest corner and trimmed back
/// with a boolean, so the end lies on the plane exactly. A curved target ends the
/// extrusion flat at the first contact: rays from sample points across the profile are
/// cast against the target's facets and the shortest hit is the reach, so the result
/// touches the surface without piercing it. (The honest end shape there would be the
/// surface itself; TODO.md records the flat-end limitation.)
///
/// Anything the semantics cannot promise is refused rather than approximated: a target
/// parallel to the direction of travel, a target any part of the profile has already
/// passed, and a curved target the extrusion never meets are each their own error.
pub fn extrude_to_face(op: OpId, profile: &Profile, target: &Face) -> Result<Solid, KernelError> {
    let profile = profile.normalised()?;
    let frame = profile.frame;
    if let SurfaceKind::Planar { normal } = target.surface {
        let along = frame.z.dot(normal);
        if along.abs() < ANGULAR_TOL {
            return Err(KernelError::TargetFaceParallel);
        }
        // Reach of every profile corner: where its travel line pierces the target plane.
        let anchor = target.centroid();
        let (mut lo, mut hi) = (f64::INFINITY, f64::NEG_INFINITY);
        for p in profile.loops().flat_map(|c| c.points.iter()) {
            let t = (anchor - frame.to_world(*p)).dot(normal) / along;
            lo = lo.min(t);
            hi = hi.max(t);
        }
        // The whole profile must lie in front of the plane. A profile that crosses it
        // would thin to nothing along the crossing line, and one behind it has nowhere
        // to go; both are refusals, not zero-thickness shells.
        if lo <= LINEAR_TOL {
            return Err(KernelError::TargetFaceBehind);
        }
        if hi - lo <= LINEAR_TOL {
            // Parallel planes: one distance serves the whole profile.
            return extrude(op, &profile, Extent::OneSide(hi));
        }
        // Tilted plane: overshoot past the farthest corner, then keep only the material
        // on the profile's side of the plane. The overshoot means the boolean never has
        // to split coincident faces, and the trim box's near cap becomes the end face,
        // lying on the target plane by construction.
        let solid = extrude(op, &profile, Extent::OneSide(hi + (hi - lo)))?;
        let back = -normal * along.signum();
        let bframe = Frame::from_normal(anchor, back);
        let aabb = solid.aabb();
        let (mut min, mut max) = (Vec2::splat(f64::INFINITY), Vec2::splat(f64::NEG_INFINITY));
        let mut depth = 0.0f64;
        for i in 0..8 {
            let corner = Vec3::new(
                if i & 1 == 0 { aabb.min.x } else { aabb.max.x },
                if i & 2 == 0 { aabb.min.y } else { aabb.max.y },
                if i & 4 == 0 { aabb.min.z } else { aabb.max.z },
            );
            let local = bframe.to_local(corner);
            min = min.min(local);
            max = max.max(local);
            depth = depth.max((corner - bframe.origin).dot(back));
        }
        // A millimetre of margin all round so the box's own sides never coincide with
        // anything they are meant to keep.
        let (min, max, depth) = (min - Vec2::splat(1.0), max + Vec2::splat(1.0), depth + 1.0);
        let keep = Contour::polygon(
            vec![min, Vec2::new(max.x, min.y), max, Vec2::new(min.x, max.y)],
            0,
        );
        let trim_op = OpId {
            feature: op.feature,
            sub: op.sub | TRIM_SUB,
        };
        let half = extrude(trim_op, &Profile::new(bframe, keep), Extent::OneSide(depth))?;
        let trimmed = boolean(&solid, &half, BoolOp::Intersect)?;
        if trimmed.is_empty() {
            return Err(KernelError::EmptyResult);
        }
        return Ok(trimmed);
    }
    // Curved target: the reach is the first contact of any point of the profile.
    // Boundary points alone would miss a bulge facing the middle of the region, so a
    // grid over the profile's interior samples that too.
    let mut samples: Vec<Vec2> = profile
        .loops()
        .flat_map(|c| c.points.iter().copied())
        .collect();
    let (mut min2, mut max2) = (Vec2::splat(f64::INFINITY), Vec2::splat(f64::NEG_INFINITY));
    for p in &samples {
        min2 = min2.min(*p);
        max2 = max2.max(*p);
    }
    const GRID: usize = 8;
    for i in 0..=GRID {
        for j in 0..=GRID {
            let p =
                min2 + (max2 - min2) * Vec2::new(i as f64 / GRID as f64, j as f64 / GRID as f64);
            if profile.contains(p) {
                samples.push(p);
            }
        }
    }
    let mut reach: Option<f64> = None;
    let mut met = false;
    for s in samples {
        let origin = frame.to_world(s);
        for poly in &target.polygons {
            let along = frame.z.dot(poly.plane.normal);
            if along.abs() < 1e-12 {
                continue;
            }
            let t = (poly.plane.origin - origin).dot(poly.plane.normal) / along;
            let pframe = Frame::from_normal(poly.plane.origin, poly.plane.normal);
            let hit = pframe.to_local(origin + frame.z * t);
            let flat: Vec<Vec2> = poly.vertices.iter().map(|v| pframe.to_local(*v)).collect();
            if !polygon_contains(&flat, hit) {
                continue;
            }
            met = true;
            if t > LINEAR_TOL {
                reach = Some(reach.map_or(t, |r: f64| r.min(t)));
            }
        }
    }
    match reach {
        Some(d) => extrude(op, &profile, Extent::OneSide(d)),
        None if met => Err(KernelError::TargetFaceBehind),
        None => Err(KernelError::TargetFaceMissed),
    }
}

/// Rotates the profile about `axis` by `angle` radians (right-handed). The axis must lie
/// in the profile plane and the profile must not cross it.
pub fn revolve(
    op: OpId,
    profile: &Profile,
    axis: &Axis,
    angle: f64,
    tess: &Tessellation,
) -> Result<Solid, KernelError> {
    let profile = profile.normalised()?;
    if angle.abs() < ANGULAR_TOL || !angle.is_finite() {
        return Err(KernelError::ZeroAngle);
    }
    let frame = profile.frame;
    let dir = axis.direction.normalize();
    if dir.dot(frame.z).abs() > 1e-6
        || frame.plane().signed_distance(axis.origin).abs() > LINEAR_TOL
    {
        return Err(KernelError::AxisNotInProfilePlane);
    }
    // Signed distance from the axis within the plane; the profile must sit on one side.
    let side_dir = frame.z.cross(dir);
    let mut max_r: f64 = 0.0;
    let (mut pos, mut neg) = (false, false);
    for p in profile.loops().flat_map(|c| c.points.iter()) {
        let s = (frame.to_world(*p) - axis.origin).dot(side_dir);
        max_r = max_r.max(s.abs());
        pos |= s > LINEAR_TOL;
        neg |= s < -LINEAR_TOL;
    }
    if pos && neg {
        return Err(KernelError::ProfileCrossesAxis);
    }
    if max_r <= LINEAR_TOL {
        return Err(KernelError::EmptyProfile);
    }

    let full = angle.abs() >= TAU - 1e-9;
    let sweep = if full { TAU * angle.signum() } else { angle };
    let n = tess
        .segment_count(max_r, sweep)
        .max(if full { 3 } else { 1 });
    let count = if full { n } else { n + 1 };
    let sections: Vec<Section> = (0..count)
        .map(|i| {
            let rot = Quat::from_axis_angle(dir, sweep * i as f64 / n as f64);
            Section::place(&profile, |p| {
                axis.origin + rot * (frame.to_world(p) - axis.origin)
            })
        })
        .collect();

    let contours: Vec<&Contour> = profile.loops().collect();
    let mut b = SolidBuilder::default();
    skin(&mut b, op, &profile, &sections, full, |l, j| {
        let c = contours[l];
        match c.segments[j].kind {
            SegmentKind::Arc { .. } => SurfaceKind::Freeform,
            SegmentKind::Line => {
                let p0 = frame.to_world(c.points[j]);
                let p1 = frame.to_world(c.points[(j + 1) % c.points.len()]);
                let r0 = (p0 - axis.origin).dot(side_dir).abs();
                let r1 = (p1 - axis.origin).dot(side_dir).abs();
                let h0 = (p0 - axis.origin).dot(dir);
                let h1 = (p1 - axis.origin).dot(dir);
                if (r1 - r0).abs() < LINEAR_TOL {
                    SurfaceKind::Cylindrical {
                        origin: axis.origin,
                        axis: dir,
                        radius: r0,
                    }
                } else if (h1 - h0).abs() < LINEAR_TOL {
                    SurfaceKind::Planar { normal: dir }
                } else {
                    // The generating line meets the axis at the apex.
                    let t = -r0 / (r1 - r0);
                    let apex = axis.origin + dir * (h0 + (h1 - h0) * t);
                    SurfaceKind::Conical {
                        apex,
                        axis: dir,
                        half_angle: (r1 - r0).abs().atan2((h1 - h0).abs()),
                    }
                }
            }
        }
    })?;
    seal(b)
}

/// Moves the profile along `path`, keeping it perpendicular to the path. The profile
/// is rotated so its normal follows the first tangent, then carried with a
/// rotation-minimising frame; at every bend the section sits in the bisecting plane so
/// neighbouring segments meet cleanly.
pub fn sweep(op: OpId, profile: &Profile, path: &Path3) -> Result<Solid, KernelError> {
    let profile = profile.normalised()?;
    let pts = path.cleaned()?;
    let frame = profile.frame;
    let tangents: Vec<Vec3> = pts.windows(2).map(|w| (w[1] - w[0]).normalize()).collect();

    // Profile points relative to the path start, in world space.
    let local: Vec<Vec<Vec3>> = profile
        .loops()
        .map(|c| {
            c.points
                .iter()
                .map(|p| frame.to_world(*p) - pts[0])
                .collect()
        })
        .collect();
    let mut rot = Quat::from_rotation_arc(frame.z, tangents[0]);
    let mut sections = Vec::with_capacity(pts.len());
    sections.push(Section {
        loops: local
            .iter()
            .map(|l| l.iter().map(|q| rot * *q + pts[0]).collect())
            .collect(),
    });
    for i in 1..pts.len() {
        let prev_t = tangents[i - 1];
        let placed = |q: &Vec3| rot * *q + pts[i];
        if i == pts.len() - 1 {
            sections.push(Section {
                loops: local
                    .iter()
                    .map(|l| l.iter().map(placed).collect())
                    .collect(),
            });
            break;
        }
        let next_t = tangents[i];
        let bisector = (prev_t + next_t)
            .try_normalize()
            .ok_or(KernelError::DegeneratePath)?;
        let denom = prev_t.dot(bisector);
        let project = |q: &Vec3| {
            let p = placed(q);
            p + prev_t * ((pts[i] - p).dot(bisector) / denom)
        };
        sections.push(Section {
            loops: local
                .iter()
                .map(|l| l.iter().map(project).collect())
                .collect(),
        });
        rot = Quat::from_rotation_arc(prev_t, next_t) * rot;
    }

    let straight = tangents.iter().all(|t| t.dot(tangents[0]) > 1.0 - 1e-12);
    let contours: Vec<&Contour> = profile.loops().collect();
    let mut b = SolidBuilder::default();
    skin(&mut b, op, &profile, &sections, false, |l, j| {
        match (straight, contours[l].segments[j].kind) {
            (true, SegmentKind::Arc { center, radius, .. }) => SurfaceKind::Cylindrical {
                origin: rot * (frame.to_world(center) - pts[0]) + pts[0],
                axis: tangents[0],
                radius,
            },
            (true, SegmentKind::Line) => SurfaceKind::Planar { normal: Vec3::ZERO },
            _ => SurfaceKind::Freeform,
        }
    })?;
    seal(b)
}

/// Skins a ruled surface through the sections in order. Every section must have the same
/// number of holes. Corners of every section are preserved: rings are merged by
/// arc-length parameter rather than resampled uniformly.
pub fn loft(op: OpId, profiles: &[Profile]) -> Result<Solid, KernelError> {
    if profiles.len() < 2 {
        return Err(KernelError::TooFewSections);
    }
    let mut sections: Vec<Profile> = profiles
        .iter()
        .map(Profile::normalised)
        .collect::<Result<_, _>>()?;
    if sections
        .iter()
        .any(|p| p.holes.len() != sections[0].holes.len())
    {
        return Err(KernelError::MismatchedHoles);
    }
    // Make every outer loop read counter-clockwise from the side the loft advances to,
    // so the ring-matching below never pairs a clockwise ring with a counter-clockwise one.
    let centroids: Vec<Vec3> = sections
        .iter()
        .map(|p| p.frame.to_world(centroid2(&p.outer)))
        .collect();
    for k in 0..sections.len() {
        let motion = if k + 1 < sections.len() {
            centroids[k + 1] - centroids[k]
        } else {
            centroids[k] - centroids[k - 1]
        };
        if sections[k].frame.z.dot(motion) < 0.0 {
            let s = &mut sections[k];
            s.outer = s.outer.reversed();
            for h in &mut s.holes {
                *h = h.reversed();
            }
        }
    }

    let loop_count = 1 + sections[0].holes.len();
    let mut b = SolidBuilder::default();
    for l in 0..loop_count {
        let rings: Vec<Vec<Vec3>> = sections
            .iter()
            .map(|p| {
                let c = if l == 0 { &p.outer } else { &p.holes[l - 1] };
                c.points.iter().map(|q| p.frame.to_world(*q)).collect()
            })
            .collect();
        let matched = match_rings(&rings);
        for k in 0..matched.len() - 1 {
            let role = if l == 0 {
                FaceRole::Side(k as u32)
            } else {
                FaceRole::Generic(((l as u32) << 16) | k as u32)
            };
            let (cur, next) = (&matched[k], &matched[k + 1]);
            let n = cur.len();
            for j in 0..n {
                let m = (j + 1) % n;
                b.push_quad(
                    FaceKey::new(op, role),
                    SurfaceKind::Freeform,
                    [cur[j], cur[m], next[m], next[j]],
                );
            }
        }
    }
    let first = Section::place(&sections[0], |p| sections[0].frame.to_world(p));
    let last_p = sections.last().unwrap();
    let last = Section::place(last_p, |p| last_p.frame.to_world(p));
    cap(
        &mut b,
        FaceKey::new(op, FaceRole::StartCap),
        &first,
        &triangulate(&sections[0])?,
        false,
    );
    cap(
        &mut b,
        FaceKey::new(op, FaceRole::EndCap),
        &last,
        &triangulate(last_p)?,
        true,
    );
    // Caps use each section's own vertices while the strips use the merged rings, so the
    // seams between them have T-junctions until healed.
    seal(b)
}

fn centroid2(c: &Contour) -> Vec2 {
    c.points.iter().sum::<Vec2>() / c.points.len() as f64
}

/// A closed ring parametrised by normalised arc length from a chosen start vertex.
struct Ring {
    points: Vec<Vec3>,
    /// `params[i]` is the parameter of `points[i]`; strictly increasing from 0.
    params: Vec<f64>,
}

impl Ring {
    fn new(points: &[Vec3], start: usize) -> Self {
        let n = points.len();
        let pts: Vec<Vec3> = (0..n).map(|i| points[(start + i) % n]).collect();
        let total: f64 = (0..n).map(|i| pts[i].distance(pts[(i + 1) % n])).sum();
        let mut params = Vec::with_capacity(n);
        let mut acc = 0.0;
        for i in 0..n {
            params.push(acc / total);
            acc += pts[i].distance(pts[(i + 1) % n]);
        }
        Self {
            points: pts,
            params,
        }
    }

    fn sample(&self, u: f64) -> Vec3 {
        let n = self.points.len();
        let i = self.params.partition_point(|p| *p <= u).saturating_sub(1);
        let j = (i + 1) % n;
        let u0 = self.params[i];
        let u1 = if j == 0 { 1.0 } else { self.params[j] };
        let t = if u1 > u0 {
            ((u - u0) / (u1 - u0)).clamp(0.0, 1.0)
        } else {
            0.0
        };
        self.points[i].lerp(self.points[j], t)
    }
}

/// Aligns each ring's start vertex to the previous ring to minimise twist, then samples
/// every ring at the union of all rings' vertex parameters so all have equal counts.
fn match_rings(rings: &[Vec<Vec3>]) -> Vec<Vec<Vec3>> {
    const PROBES: usize = 64;
    let mut aligned: Vec<Ring> = Vec::with_capacity(rings.len());
    aligned.push(Ring::new(&rings[0], 0));
    for ring in &rings[1..] {
        let prev = aligned.last().unwrap();
        let reference: Vec<Vec3> = (0..PROBES)
            .map(|i| prev.sample(i as f64 / PROBES as f64))
            .collect();
        let best = (0..ring.len())
            .map(|start| {
                let candidate = Ring::new(ring, start);
                let cost: f64 = reference
                    .iter()
                    .enumerate()
                    .map(|(i, r)| {
                        candidate
                            .sample(i as f64 / PROBES as f64)
                            .distance_squared(*r)
                    })
                    .sum();
                (cost, start)
            })
            .min_by(|a, b| a.0.total_cmp(&b.0))
            .map(|(_, s)| s)
            .unwrap_or(0);
        aligned.push(Ring::new(ring, best));
    }
    let mut params: Vec<f64> = aligned
        .iter()
        .flat_map(|r| r.params.iter().copied())
        .collect();
    params.sort_by(f64::total_cmp);
    params.dedup_by(|a, b| (*a - *b).abs() < 1e-9);
    aligned
        .iter()
        .map(|r| params.iter().map(|u| r.sample(*u)).collect())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::Segment;
    use approx::assert_relative_eq;
    use basset_math::Frame;
    use std::f64::consts::PI;

    /// Rectangle whose four edges come from four distinct curves, as a sketch would give.
    fn rect(w: f64, h: f64) -> Contour {
        let mut c = Contour::polygon(
            vec![
                Vec2::ZERO,
                Vec2::new(w, 0.0),
                Vec2::new(w, h),
                Vec2::new(0.0, h),
            ],
            0,
        );
        for (i, s) in c.segments.iter_mut().enumerate() {
            s.curve = i as u32;
        }
        c
    }

    fn fine() -> Tessellation {
        Tessellation {
            chord_tolerance: 1e-4,
            max_segment_angle: 2f64.to_radians(),
        }
    }

    /// A profile that doubles back on itself builds side faces that cancel out, and the
    /// shell used to come back with a hole in it: closed enough to look right, and wrong
    /// the moment a boolean or an export met it. Generators now heal and check, so what
    /// they return is closed or is an error — never a leaking body.
    #[test]
    fn a_profile_that_touches_itself_still_yields_a_closed_shell() {
        let points = vec![
            Vec2::ZERO,
            Vec2::new(10.0, 0.0),
            Vec2::new(10.0, 10.0),
            // Out to a spike and back to within a whisker of where it left.
            Vec2::new(10.0, 15.0),
            Vec2::new(10.0, 10.000_1),
            Vec2::new(0.0, 10.0),
        ];
        let profile = Profile {
            frame: Frame::XY,
            outer: Contour::polygon(points, 0),
            holes: vec![],
        };
        let s = extrude(OpId::new(1), &profile, Extent::OneSide(5.0)).expect("healed");
        assert!(s.is_closed(), "{:?}", s.validate());
        assert_relative_eq!(s.volume(), 500.0, epsilon = 1e-2);
    }

    #[test]
    fn extrude_rectangle_with_hole() {
        let outer = rect(4.0, 3.0);
        let hole = Contour::circle(Vec2::new(2.0, 1.5), 0.5, 9, &fine());
        let profile = Profile {
            frame: Frame::XY,
            outer,
            holes: vec![hole],
        };
        let s = extrude(OpId::new(1), &profile, Extent::OneSide(2.0)).unwrap();
        assert_relative_eq!(s.volume(), (12.0 - PI * 0.25) * 2.0, epsilon = 1e-3);
        assert!(s.is_closed(), "{:?}", s.validate());
        assert_eq!(
            s.faces.len(),
            7,
            "two caps, four sides, one cylindrical hole"
        );
        let hole_face = s
            .face(FaceKey::new(OpId::new(1), FaceRole::Side(9)))
            .unwrap();
        assert!(
            matches!(hole_face.surface, SurfaceKind::Cylindrical { radius, .. } if radius == 0.5)
        );
        assert_eq!(s.aabb().max.z, 2.0);
        // Both caps have the expected orientation.
        let top = s
            .face(FaceKey::new(OpId::new(1), FaceRole::EndCap))
            .unwrap();
        assert_eq!(top.surface, SurfaceKind::Planar { normal: Vec3::Z });
    }

    #[test]
    fn extrude_negative_and_symmetric_extents() {
        let profile = Profile::new(Frame::XY, rect(1.0, 1.0));
        let down = extrude(OpId::new(1), &profile, Extent::OneSide(-3.0)).unwrap();
        assert_relative_eq!(down.volume(), 3.0, epsilon = 1e-9);
        assert_relative_eq!(down.aabb().min.z, -3.0);
        let sym = extrude(OpId::new(1), &profile, Extent::Symmetric(4.0)).unwrap();
        assert_relative_eq!(sym.aabb().min.z, -2.0);
        assert_relative_eq!(sym.aabb().max.z, 2.0);
        assert!(sym.is_closed());
    }

    #[test]
    fn extrude_clockwise_profile_still_faces_outward() {
        let profile = Profile::new(Frame::XY, rect(2.0, 2.0).reversed());
        let s = extrude(OpId::new(1), &profile, Extent::OneSide(1.0)).unwrap();
        assert_relative_eq!(s.volume(), 4.0, epsilon = 1e-9);
        assert!(s.is_closed());
    }

    #[test]
    fn extrude_on_tilted_frame() {
        let frame = Frame::from_normal(Vec3::new(1.0, 2.0, 3.0), Vec3::new(1.0, 1.0, 0.0));
        let s = extrude(
            OpId::new(1),
            &Profile::new(frame, rect(2.0, 3.0)),
            Extent::OneSide(5.0),
        )
        .unwrap();
        assert_relative_eq!(s.volume(), 30.0, epsilon = 1e-9);
        assert!(s.is_closed());
    }

    #[test]
    fn revolve_full_cylinder_and_partial() {
        // Rectangle from r=0..2 along the axis, height 3, revolved around Y.
        let profile = Profile::new(Frame::XY, rect(2.0, 3.0));
        let axis = Axis::new(Vec3::ZERO, Vec3::Y);
        let full = revolve(OpId::new(1), &profile, &axis, TAU, &fine()).unwrap();
        assert_relative_eq!(full.volume(), PI * 4.0 * 3.0, epsilon = 0.05);
        assert!(full.is_closed(), "{:?}", full.validate());
        assert_eq!(
            full.faces.len(),
            3,
            "top disc, bottom disc, cylinder; no seam, no axis face"
        );
        let half = revolve(OpId::new(1), &profile, &axis, PI, &fine()).unwrap();
        assert_relative_eq!(half.volume(), PI * 4.0 * 3.0 / 2.0, epsilon = 0.05);
        assert!(half.is_closed());
        assert_eq!(half.faces.len(), 5);
        let neg = revolve(OpId::new(1), &profile, &axis, -PI / 2.0, &fine()).unwrap();
        assert_relative_eq!(neg.volume(), PI * 4.0 * 3.0 / 4.0, epsilon = 0.05);
    }

    #[test]
    fn revolve_torus() {
        let circle = Contour::circle(Vec2::new(5.0, 0.0), 1.0, 3, &fine());
        let torus = revolve(
            OpId::new(1),
            &Profile::new(Frame::XY, circle),
            &Axis::new(Vec3::ZERO, Vec3::Y),
            TAU,
            &fine(),
        )
        .unwrap();
        assert_relative_eq!(torus.volume(), 2.0 * PI * PI * 5.0, epsilon = 0.5);
        assert!(torus.is_closed());
        assert_eq!(torus.faces.len(), 1);
    }

    #[test]
    fn revolve_rejects_bad_axes() {
        let profile = Profile::new(
            Frame::XY,
            Contour::polygon(
                vec![
                    Vec2::new(-1.0, 0.0),
                    Vec2::new(1.0, 0.0),
                    Vec2::new(0.0, 1.0),
                ],
                0,
            ),
        );
        let e = revolve(
            OpId::new(1),
            &profile,
            &Axis::new(Vec3::ZERO, Vec3::Y),
            PI,
            &fine(),
        );
        assert_eq!(e, Err(KernelError::ProfileCrossesAxis));
        let e = revolve(
            OpId::new(1),
            &profile,
            &Axis::new(Vec3::ZERO, Vec3::Z),
            PI,
            &fine(),
        );
        assert_eq!(e, Err(KernelError::AxisNotInProfilePlane));
    }

    #[test]
    fn sweep_straight_matches_extrude() {
        let profile = Profile::new(Frame::XY, rect(1.0, 2.0));
        let path = Path3 {
            points: vec![Vec3::ZERO, Vec3::new(0.0, 0.0, 5.0)],
        };
        let s = sweep(OpId::new(1), &profile, &path).unwrap();
        assert_relative_eq!(s.volume(), 10.0, epsilon = 1e-9);
        assert!(s.is_closed());
    }

    #[test]
    fn sweep_along_bent_path_keeps_cross_section() {
        let profile = Profile::new(Frame::XY, Contour::circle(Vec2::ZERO, 0.5, 1, &fine()));
        let path = Path3 {
            points: vec![
                Vec3::ZERO,
                Vec3::new(0.0, 0.0, 4.0),
                Vec3::new(3.0, 0.0, 4.0),
            ],
        };
        let s = sweep(OpId::new(1), &profile, &path).unwrap();
        // Mitred bend: volume equals area × path length exactly for a right angle.
        assert_relative_eq!(s.volume(), PI * 0.25 * 7.0, epsilon = 0.01);
        assert!(s.is_closed(), "{:?}", s.validate());
    }

    #[test]
    fn loft_square_to_rotated_square_and_to_circle() {
        let bottom = Profile::new(Frame::XY, rect(2.0, 2.0));
        let top = Profile::new(
            Frame {
                origin: Vec3::new(0.0, 0.0, 3.0),
                ..Frame::XY
            },
            rect(2.0, 2.0),
        );
        let prism = loft(OpId::new(1), &[bottom.clone(), top]).unwrap();
        assert_relative_eq!(prism.volume(), 12.0, epsilon = 1e-9);
        assert!(prism.is_closed(), "{:?}", prism.validate());

        let circle = Contour::circle(Vec2::new(1.0, 1.0), 1.0, 5, &Tessellation::default());
        let top = Profile::new(
            Frame {
                origin: Vec3::new(0.0, 0.0, 3.0),
                ..Frame::XY
            },
            circle,
        );
        let l = loft(OpId::new(2), &[bottom, top]).unwrap();
        assert!(l.is_closed(), "{:?}", l.validate());
        // Between the prism (12) and the cylinder (3π ≈ 9.42).
        assert!(l.volume() > 9.4 && l.volume() < 12.0, "{}", l.volume());
    }

    #[test]
    fn loft_accepts_flipped_frames_and_holes() {
        let hole = Contour::circle(Vec2::new(1.0, 1.0), 0.3, 7, &Tessellation::default());
        let bottom = Profile {
            frame: Frame::XY,
            outer: rect(2.0, 2.0),
            holes: vec![hole.clone()],
        };
        // Top section's frame points down, as it would if sketched on a face's underside.
        let flipped = Frame {
            origin: Vec3::new(0.0, 0.0, 2.0),
            x: Vec3::X,
            y: -Vec3::Y,
            z: -Vec3::Z,
        };
        let top = Profile {
            frame: flipped,
            outer: rect(2.0, 2.0),
            holes: vec![hole],
        };
        let l = loft(OpId::new(1), &[bottom, top]).unwrap();
        assert!(l.is_closed(), "{:?}", l.validate());
        assert_relative_eq!(l.volume(), (4.0 - PI * 0.09) * 2.0, epsilon = 0.02);
        let mismatch = loft(
            OpId::new(1),
            &[
                Profile::new(Frame::XY, rect(1.0, 1.0)),
                Profile::new(flipped, rect(1.0, 1.0)),
            ],
        );
        assert!(mismatch.is_ok());
        let bad = loft(
            OpId::new(1),
            &[
                Profile::new(Frame::XY, rect(1.0, 1.0)),
                l_with_hole(flipped),
            ],
        );
        assert_eq!(bad, Err(KernelError::MismatchedHoles));
    }

    fn l_with_hole(frame: Frame) -> Profile {
        let hole = Contour::circle(Vec2::new(0.5, 0.5), 0.1, 7, &Tessellation::default());
        Profile {
            frame,
            outer: rect(1.0, 1.0),
            holes: vec![hole],
        }
    }

    #[test]
    fn line_segments_get_planar_faces_with_stable_keys() {
        let mut c = rect(1.0, 1.0);
        c.segments[2] = Segment::line(42);
        let s = extrude(
            OpId::new(3),
            &Profile::new(Frame::XY, c),
            Extent::OneSide(1.0),
        )
        .unwrap();
        let f = s
            .face(FaceKey::new(OpId::new(3), FaceRole::Side(42)))
            .unwrap();
        assert_eq!(f.surface, SurfaceKind::Planar { normal: Vec3::Y });
    }

    /// The face of `solid` carrying `key`, for handing to `extrude_to_face` the way the
    /// timeline resolves a stored face reference.
    fn face_of(solid: &Solid, key: FaceKey) -> &Face {
        solid.face(key).expect("the target face exists")
    }

    /// A target parallel to the profile plane is the plain case: one distance reaches
    /// the whole profile, and the reach is measured to the face's plane even where the
    /// profile does not sit underneath the face itself.
    #[test]
    fn extrude_to_a_parallel_face_reaches_its_plane_exactly() {
        let target = crate::primitives::cuboid(
            OpId::new(9),
            Vec3::new(20.0, 20.0, 3.0),
            Vec3::new(30.0, 30.0, 5.0),
        );
        let bottom = face_of(&target, FaceKey::new(OpId::new(9), FaceRole::StartCap));
        let profile = Profile::new(Frame::XY, rect(4.0, 2.0));
        let s = extrude_to_face(OpId::new(1), &profile, bottom).unwrap();
        assert!(s.is_closed(), "{:?}", s.validate());
        assert_relative_eq!(s.volume(), 4.0 * 2.0 * 3.0, epsilon = 1e-9);
        assert_relative_eq!(s.aabb().max.z, 3.0, epsilon = 1e-9);
    }

    /// A tilted planar target: the reach differs across the profile, so the extrusion is
    /// trimmed back to the plane and the volume is the integral of the varying height.
    #[test]
    fn extrude_to_a_tilted_face_ends_on_its_plane() {
        // A slab whose start cap lies on the plane through (0, 0, 8) with normal
        // (1, 0, 1)/√2; over the unit-ish profile below, the height is 8 − x.
        let tilted = Frame::from_normal(Vec3::new(0.0, 0.0, 8.0), Vec3::new(1.0, 0.0, 1.0));
        let slab = extrude(
            OpId::new(9),
            &Profile::new(tilted, rect(40.0, 40.0)),
            Extent::OneSide(5.0),
        )
        .unwrap();
        let face = face_of(&slab, FaceKey::new(OpId::new(9), FaceRole::StartCap));
        let profile = Profile::new(Frame::XY, rect(2.0, 2.0));
        let s = extrude_to_face(OpId::new(1), &profile, face).unwrap();
        assert!(s.is_closed(), "{:?}", s.validate());
        // ∫₀²∫₀² (8 − x) dy dx = 2 · (16 − 2) = 28.
        assert_relative_eq!(s.volume(), 28.0, epsilon = 1e-6);
        // Every point of the trimmed end lies on the target plane, none past it.
        let plane = basset_math::Plane::new(tilted.origin, tilted.z);
        let past = s
            .faces
            .iter()
            .flat_map(|f| f.polygons.iter())
            .flat_map(|p| p.vertices.iter())
            .map(|v| plane.signed_distance(*v))
            .fold(f64::NEG_INFINITY, f64::max);
        assert!(past.abs() < 1e-6, "material reaches {past} past the plane");
    }

    /// The refusals: a target the travel direction runs along, and one the profile has
    /// already passed, are errors rather than degenerate solids.
    #[test]
    fn extrude_to_face_refuses_parallel_and_behind_targets() {
        let target = crate::primitives::cuboid(
            OpId::new(9),
            Vec3::new(0.0, 20.0, -5.0),
            Vec3::new(10.0, 30.0, -3.0),
        );
        let profile = Profile::new(Frame::XY, rect(4.0, 2.0));
        // The −y side face stands parallel to the profile's travel along +z.
        let side = face_of(&target, FaceKey::new(OpId::new(9), FaceRole::Side(0)));
        assert_eq!(
            extrude_to_face(OpId::new(1), &profile, side).unwrap_err(),
            KernelError::TargetFaceParallel
        );
        // The slab's top cap sits at z = −3, behind a profile on the XY plane.
        let top = face_of(&target, FaceKey::new(OpId::new(9), FaceRole::EndCap));
        assert_eq!(
            extrude_to_face(OpId::new(1), &profile, top).unwrap_err(),
            KernelError::TargetFaceBehind
        );
    }

    /// A curved target ends the extrusion flat at the first contact: a square pushed at
    /// the side of a cylinder stops where the closest generator line of the cylinder is.
    #[test]
    fn extrude_to_a_cylinder_side_stops_at_first_contact() {
        // Cylinder along y, axis through (0, ·, 10), radius 4: its lowest line is z = 6.
        let cyl = crate::primitives::cylinder(
            OpId::new(9),
            Vec3::new(0.0, -10.0, 10.0),
            Vec3::Y,
            4.0,
            20.0,
            &fine(),
        );
        let side = face_of(&cyl, FaceKey::new(OpId::new(9), FaceRole::Side(0)));
        // A 2×2 square centred under the axis, so a grid sample sits at x = 0 exactly.
        let mut c = rect(2.0, 2.0);
        for p in &mut c.points {
            *p -= Vec2::new(1.0, 1.0);
        }
        let profile = Profile::new(Frame::XY, c);
        let s = extrude_to_face(OpId::new(1), &profile, side).unwrap();
        assert!(s.is_closed(), "{:?}", s.validate());
        assert_relative_eq!(s.aabb().max.z, 6.0, epsilon = 1e-3);
        assert_relative_eq!(s.volume(), 4.0 * 6.0, epsilon = 0.02);

        // Aimed past the cylinder entirely, the same profile is refused.
        let mut miss = rect(2.0, 2.0);
        for p in &mut miss.points {
            *p += Vec2::new(20.0, 0.0);
        }
        assert_eq!(
            extrude_to_face(OpId::new(1), &Profile::new(Frame::XY, miss), side).unwrap_err(),
            KernelError::TargetFaceMissed
        );
    }
}
