//! Stable identity for faces and edges.
//!
//! Faces are never referred to by array position. A [`FaceKey`] names the operation that
//! created the face and the *role* it played in that operation, both of which are
//! deterministic functions of the feature's inputs. Editing an extrude's distance
//! therefore yields a solid whose faces carry exactly the same keys as before, and
//! downstream fillets or sketches attached to those keys keep working. This is the
//! kernel's half of the topological naming problem; the other half lives in
//! `basset-core`, which chooses the [`OpId`]s.

use serde::{Deserialize, Serialize};

/// Which timeline operation produced a face. `feature` is the feature id; `sub` separates
/// solids produced by one feature from several profiles, so their caps do not collide.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd, Debug, Serialize, Deserialize)]
pub struct OpId {
    pub feature: u64,
    pub sub: u32,
}

impl OpId {
    pub const fn new(feature: u64) -> Self {
        Self { feature, sub: 0 }
    }

    pub const fn with_sub(self, sub: u32) -> Self {
        Self { sub, ..self }
    }
}

/// The part a face played in the operation that created it.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd, Debug, Serialize, Deserialize)]
pub enum FaceRole {
    /// The cap on the profile plane (extrude/revolve/sweep) or the first section (loft).
    StartCap,
    /// The cap at the far end.
    EndCap,
    /// A lateral face generated by one profile curve. The payload is the curve tag the
    /// profile carried, so it survives re-tessellation and re-solving of the sketch.
    Side(u32),
    /// The rounded surface created by filleting the n-th selected edge.
    Fillet(u32),
    /// The flat surface created by chamfering the n-th selected edge.
    Chamfer(u32),
    /// Anything without a more specific meaning (loft hole strips, tool scaffolding).
    Generic(u32),
}

#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd, Debug, Serialize, Deserialize)]
pub struct FaceKey {
    pub op: OpId,
    pub role: FaceRole,
}

impl FaceKey {
    pub const fn new(op: OpId, role: FaceRole) -> Self {
        Self { op, role }
    }
}

/// An edge is the boundary between two faces, so its identity is the unordered pair of
/// face keys. Normalised on construction so equality does not depend on argument order.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd, Debug, Serialize, Deserialize)]
pub struct EdgeKey {
    pub a: FaceKey,
    pub b: FaceKey,
}

impl EdgeKey {
    pub fn new(x: FaceKey, y: FaceKey) -> Self {
        if x <= y {
            Self { a: x, b: y }
        } else {
            Self { a: y, b: x }
        }
    }

    pub fn touches(&self, face: FaceKey) -> bool {
        self.a == face || self.b == face
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn edge_key_is_order_independent() {
        let op = OpId::new(3);
        let x = FaceKey::new(op, FaceRole::StartCap);
        let y = FaceKey::new(op, FaceRole::Side(2));
        assert_eq!(EdgeKey::new(x, y), EdgeKey::new(y, x));
        assert!(EdgeKey::new(x, y).touches(y));
    }

    #[test]
    fn sub_operations_do_not_collide() {
        let a = FaceKey::new(OpId::new(1), FaceRole::EndCap);
        let b = FaceKey::new(OpId::new(1).with_sub(1), FaceRole::EndCap);
        assert_ne!(a, b);
    }
}
