//! Solid modelling kernel for Basset.
//!
//! # Representation
//!
//! A [`Solid`] is a polygonal boundary representation with *analytic provenance*: every
//! [`Face`] is a set of planar convex polygons plus the [`SurfaceKind`] the operation that
//! made it knows it to be (a cylinder of radius r, a plane, …). Curved surfaces are
//! faceted when created, at a resolution controlled by [`Tessellation`]. This single
//! representation lets extrude, revolve, sweep, loft, booleans, fillets and chamfers all
//! work end-to-end today; the public API is shaped so an exact analytic B-rep can replace
//! the internals later without touching `basset-core`.
//!
//! # Identity
//!
//! Faces carry a [`FaceKey`] naming the operation and the role the face played in it, and
//! edges are the unordered pair of adjacent face keys ([`EdgeKey`]). Booleans preserve
//! the keys of surviving fragments, so a fillet applied to "the edge between the top cap
//! of extrude 2 and the side generated by curve 3" keeps working after extrude 2 changes
//! its distance.
//!
//! # Conventions
//!
//! Millimetres and radians; polygons wind counter-clockwise about the outward normal;
//! profiles are normalised to counter-clockwise outer loops with clockwise holes.

pub mod blend;
pub mod csg;
pub mod error;
pub mod generate;
pub mod geometry;
pub mod ids;
pub mod pick;
pub mod primitives;
pub mod solid;

pub use blend::{chamfer, fillet};
pub use csg::{BoolOp, boolean};
pub use error::KernelError;
pub use generate::{extrude, loft, revolve, sweep};
pub use geometry::{Axis, Contour, Extent, Path3, Profile, Segment, SegmentKind, Tessellation};
pub use ids::{EdgeKey, FaceKey, FaceRole, OpId};
pub use pick::{EdgePick, FacePick, VertexPick, corners, pick_edge, pick_face, pick_vertex};
pub use solid::{Edge, EdgeSegment, Face, Polygon, Solid, SurfaceKind, Tessellated};
