// @generated by assets/symbols/gen.py from assets/symbols/symbols.json.
// Edit the SVG there and rerun the script; do not edit this file by hand.

use super::symbols::{Ink, Paint, Path, Pen, Prim, Symbol};

#[rustfmt::skip]
pub(super) fn prims(symbol: Symbol) -> &'static [Prim] {
    match symbol {
        // Create Sketch
        Symbol::CreateSketch => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[2.5, 15.0], [11.5, 10.5], [20.5, 15.0], [11.5, 19.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[13.5, 15.2], [13.36, 15.72], [12.96, 16.2], [12.33, 16.61], [11.5, 16.93], [10.54, 17.13], [9.5, 17.2], [8.46, 17.13], [7.5, 16.93], [6.67, 16.61], [6.04, 16.2], [5.64, 15.72], [5.5, 15.2], [5.64, 14.68], [6.04, 14.2], [6.67, 13.79], [7.5, 13.47], [8.46, 13.27], [9.5, 13.2], [10.54, 13.27], [11.5, 13.47], [12.33, 13.79], [12.96, 14.2], [13.36, 14.68]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[13.5, 15.2], [16.5, 14.0], [20.1, 9.2], [17.7, 7.4], [14.1, 12.2]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.1, 12.2], [16.5, 14.0]], closed: false, tris: &[] }] },
        ],
        // Extrude
        Symbol::Extrude => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 16.0], [5.94, 12.5], [12.0, 9.0], [18.06, 12.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 16.0], [5.94, 12.5], [5.94, 17.5], [12.0, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[12.0, 16.0], [18.06, 12.5], [18.06, 17.5], [12.0, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 21.0], [5.94, 17.5], [5.94, 12.5], [12.0, 9.0], [18.06, 12.5], [18.06, 17.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.94, 12.5], [12.0, 16.0], [18.06, 12.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 16.0], [12.0, 21.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 12.5], [12.0, 2.8]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.21, 5.4], [12.0, 2.8], [9.79, 5.4]], closed: false, tris: &[] }] },
        ],
        // Revolve
        Symbol::Revolve => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[7.0, 5.0], [6.07, 6.72], [5.61, 8.28], [5.53, 9.72], [5.74, 11.08], [6.12, 12.38], [6.6, 13.64], [7.08, 14.9], [7.45, 16.2], [7.62, 17.56], [7.5, 19.0], [7.65, 19.47], [8.1, 19.9], [8.82, 20.27], [9.75, 20.56], [10.84, 20.74], [12.0, 20.8], [13.16, 20.74], [14.25, 20.56], [15.18, 20.27], [15.9, 19.9], [16.35, 19.47], [16.5, 19.0], [16.38, 17.56], [16.55, 16.2], [16.92, 14.9], [17.4, 13.64], [17.88, 12.38], [18.26, 11.08], [18.47, 9.72], [18.39, 8.28], [17.93, 6.71], [17.0, 5.0]], closed: true, tris: &[[0, 32, 31], [0, 31, 30], [0, 30, 29], [0, 29, 28], [0, 28, 27], [0, 27, 26], [0, 26, 25], [0, 25, 24], [0, 24, 23], [0, 23, 22], [0, 22, 21], [0, 21, 20], [0, 20, 19], [0, 19, 18], [0, 18, 17], [0, 17, 16], [0, 16, 15], [0, 15, 14], [0, 14, 13], [0, 13, 12], [12, 11, 10], [12, 10, 9], [0, 12, 9], [0, 9, 8], [0, 8, 7], [0, 7, 6], [0, 6, 5], [0, 5, 4], [0, 4, 3], [0, 3, 2], [2, 1, 0]] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[17.0, 5.0], [16.83, 5.52], [16.33, 6.0], [15.54, 6.41], [14.5, 6.73], [13.29, 6.93], [12.0, 7.0], [10.71, 6.93], [9.5, 6.73], [8.46, 6.41], [7.67, 6.0], [7.17, 5.52], [7.0, 5.0], [7.17, 4.48], [7.67, 4.0], [8.46, 3.59], [9.5, 3.27], [10.71, 3.07], [12.0, 3.0], [13.29, 3.07], [14.5, 3.27], [15.54, 3.59], [16.33, 4.0], [16.83, 4.48]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.0, 5.0], [6.07, 6.72], [5.61, 8.28], [5.53, 9.72], [5.74, 11.08], [6.12, 12.38], [6.6, 13.64], [7.08, 14.9], [7.45, 16.2], [7.62, 17.56], [7.5, 19.0], [7.65, 19.47], [8.1, 19.9], [8.82, 20.27], [9.75, 20.56], [10.84, 20.74], [12.0, 20.8], [13.16, 20.74], [14.25, 20.56], [15.18, 20.27], [15.9, 19.9], [16.35, 19.47], [16.5, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 0.28 }), stroke: None, paths: &[Path { pts: &[[12.0, 5.0], [17.0, 5.0], [17.93, 6.72], [18.39, 8.28], [18.47, 9.72], [18.26, 11.08], [17.88, 12.38], [17.4, 13.64], [16.92, 14.9], [16.55, 16.2], [16.38, 17.56], [16.5, 19.0], [12.0, 19.0]], closed: true, tris: &[[12, 0, 1], [12, 1, 2], [12, 2, 3], [12, 3, 4], [12, 4, 5], [12, 5, 6], [12, 6, 7], [12, 7, 8], [12, 8, 9], [12, 9, 10], [10, 11, 12]] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[17.0, 5.0], [17.93, 6.72], [18.39, 8.28], [18.47, 9.72], [18.26, 11.08], [17.88, 12.38], [17.4, 13.64], [16.92, 14.9], [16.55, 16.2], [16.38, 17.56], [16.5, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 2.0], [12.0, 22.0]], closed: false, tris: &[] }] },
        ],
        // Sweep
        Symbol::Sweep => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[4.0, 15.4], [5.84, 15.3], [7.54, 14.99], [9.08, 14.48], [10.46, 13.77], [11.7, 12.85], [12.78, 11.73], [13.72, 10.4], [14.5, 8.87], [15.12, 7.14], [15.6, 5.2], [20.4, 5.2], [19.88, 8.13], [19.1, 10.74], [18.08, 13.05], [16.82, 15.06], [15.3, 16.75], [13.54, 18.14], [11.52, 19.21], [9.26, 19.98], [6.76, 20.45], [4.0, 20.6]], closed: true, tris: &[[21, 0, 1], [21, 1, 2], [21, 2, 3], [21, 3, 4], [21, 4, 5], [9, 10, 11], [8, 9, 11], [7, 8, 11], [6, 7, 11], [5, 6, 11], [21, 5, 11], [21, 11, 12], [21, 12, 13], [21, 13, 14], [21, 14, 15], [21, 15, 16], [21, 16, 17], [21, 17, 18], [21, 18, 19], [19, 20, 21]] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.0, 15.4], [5.84, 15.3], [7.54, 14.99], [9.08, 14.48], [10.46, 13.77], [11.7, 12.85], [12.78, 11.73], [13.72, 10.4], [14.5, 8.87], [15.12, 7.14], [15.6, 5.2]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.0, 20.6], [6.76, 20.45], [9.26, 19.98], [11.52, 19.21], [13.54, 18.14], [15.3, 16.75], [16.82, 15.06], [18.08, 13.05], [19.1, 10.74], [19.88, 8.13], [20.4, 5.2]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.4, 5.2], [20.22, 5.66], [19.7, 6.05], [18.92, 6.31], [18.0, 6.4], [17.08, 6.31], [16.3, 6.05], [15.78, 5.66], [15.6, 5.2], [15.78, 4.74], [16.3, 4.35], [17.08, 4.09], [18.0, 4.0], [18.92, 4.09], [19.7, 4.35], [20.22, 4.74]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.1, 18.0], [5.06, 18.67], [4.95, 19.3], [4.78, 19.84], [4.55, 20.25], [4.28, 20.51], [4.0, 20.6], [3.72, 20.51], [3.45, 20.25], [3.22, 19.84], [3.05, 19.3], [2.94, 18.67], [2.9, 18.0], [2.94, 17.33], [3.05, 16.7], [3.22, 16.16], [3.45, 15.75], [3.72, 15.49], [4.0, 15.4], [4.28, 15.49], [4.55, 15.75], [4.78, 16.16], [4.95, 16.7], [5.06, 17.33]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[4.0, 18.0], [6.3, 17.87], [8.4, 17.49], [10.3, 16.85], [12.0, 15.95], [13.5, 14.8], [14.8, 13.39], [15.9, 11.73], [16.8, 9.81], [17.5, 7.63], [18.0, 5.2]], closed: false, tris: &[] }] },
        ],
        // Loft
        Symbol::Loft => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[4.5, 17.5], [12.0, 13.75], [19.5, 17.5], [12.0, 21.25]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.5, 17.5], [8.0, 5.5]], closed: false, tris: &[] }, Path { pts: &[[19.5, 17.5], [16.0, 5.5]], closed: false, tris: &[] }, Path { pts: &[[12.0, 21.25], [12.0, 19.45], [12.0, 17.74], [12.0, 16.13], [12.0, 14.61], [12.0, 13.19], [12.0, 11.86], [12.0, 10.63], [12.0, 9.49], [12.0, 8.45], [12.0, 7.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.5, 17.5], [12.0, 13.75], [19.5, 17.5], [12.0, 21.25]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[16.0, 5.5], [15.86, 6.02], [15.46, 6.5], [14.83, 6.91], [14.0, 7.23], [13.04, 7.43], [12.0, 7.5], [10.96, 7.43], [10.0, 7.23], [9.17, 6.91], [8.54, 6.5], [8.14, 6.02], [8.0, 5.5], [8.14, 4.98], [8.54, 4.5], [9.17, 4.09], [10.0, 3.77], [10.96, 3.57], [12.0, 3.5], [13.04, 3.57], [14.0, 3.77], [14.83, 4.09], [15.46, 4.5], [15.86, 4.98]], closed: true, tris: &[] }] },
        ],
        // Fillet
        Symbol::Fillet => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[8.88, 11.2], [4.9, 8.9], [12.0, 4.8], [15.98, 7.1]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[4.9, 8.9], [8.88, 11.2], [12.0, 16.6], [12.0, 21.0], [4.9, 16.9]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[12.0, 16.6], [19.1, 12.5], [19.1, 16.9], [12.0, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[15.98, 7.1], [12.0, 4.8], [4.9, 8.9], [4.9, 16.9], [12.0, 21.0], [19.1, 16.9], [19.1, 12.5]], closed: false, tris: &[] }, Path { pts: &[[4.9, 8.9], [8.88, 11.2]], closed: false, tris: &[] }, Path { pts: &[[12.0, 16.6], [12.0, 21.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 0.28 }), stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.88, 11.2], [15.98, 7.1], [16.57, 7.48], [17.1, 7.89], [17.57, 8.34], [17.98, 8.83], [18.32, 9.35], [18.6, 9.91], [18.82, 10.5], [18.98, 11.13], [19.07, 11.8], [19.1, 12.5], [12.0, 16.6], [11.97, 15.9], [11.88, 15.23], [11.72, 14.6], [11.5, 14.01], [11.22, 13.45], [10.88, 12.93], [10.47, 12.44], [10.0, 11.99], [9.47, 11.58]], closed: true, tris: &[[21, 0, 1], [21, 1, 2], [21, 2, 3], [21, 3, 4], [21, 4, 5], [21, 5, 6], [21, 6, 7], [21, 7, 8], [21, 8, 9], [21, 9, 10], [21, 10, 11], [11, 12, 13], [11, 13, 14], [11, 14, 15], [11, 15, 16], [11, 16, 17], [11, 17, 18], [11, 18, 19], [11, 19, 20], [11, 20, 21]] }] },
        ],
        // Chamfer
        Symbol::Chamfer => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[8.88, 11.2], [4.9, 8.9], [12.0, 4.8], [15.98, 7.1]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[4.9, 8.9], [8.88, 11.2], [12.0, 16.6], [12.0, 21.0], [4.9, 16.9]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[12.0, 16.6], [19.1, 12.5], [19.1, 16.9], [12.0, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[15.98, 7.1], [12.0, 4.8], [4.9, 8.9], [4.9, 16.9], [12.0, 21.0], [19.1, 16.9], [19.1, 12.5]], closed: false, tris: &[] }, Path { pts: &[[4.9, 8.9], [8.88, 11.2]], closed: false, tris: &[] }, Path { pts: &[[12.0, 16.6], [12.0, 21.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 0.28 }), stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.88, 11.2], [15.98, 7.1], [19.1, 12.5], [12.0, 16.6]], closed: true, tris: &[] }] },
        ],
        // Thread
        Symbol::Thread => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[7.0, 5.5], [7.0, 19.0], [7.2, 19.62], [7.79, 20.19], [8.73, 20.66], [9.92, 21.0], [11.29, 21.18], [12.71, 21.18], [14.08, 21.0], [15.27, 20.66], [16.21, 20.19], [16.8, 19.62], [17.0, 19.0], [17.0, 5.5]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[17.0, 5.5], [16.83, 6.07], [16.33, 6.6], [15.54, 7.06], [14.5, 7.41], [13.29, 7.63], [12.0, 7.7], [10.71, 7.63], [9.5, 7.41], [8.46, 7.06], [7.67, 6.6], [7.17, 6.07], [7.0, 5.5], [7.17, 4.93], [7.67, 4.4], [8.46, 3.94], [9.5, 3.59], [10.71, 3.37], [12.0, 3.3], [13.29, 3.37], [14.5, 3.59], [15.54, 3.94], [16.33, 4.4], [16.83, 4.93]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.0, 5.5], [7.0, 19.0], [7.2, 19.62], [7.79, 20.19], [8.73, 20.66], [9.92, 21.0], [11.29, 21.18], [12.71, 21.18], [14.08, 21.0], [15.27, 20.66], [16.21, 20.19], [16.8, 19.62], [17.0, 19.0], [17.0, 5.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.0, 9.6], [8.0, 10.16], [9.0, 10.56], [10.0, 10.8], [11.0, 10.88], [12.0, 10.8], [13.0, 10.56], [14.0, 10.16], [15.0, 9.6], [16.0, 8.88], [17.0, 8.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.0, 13.2], [8.0, 13.76], [9.0, 14.16], [10.0, 14.4], [11.0, 14.48], [12.0, 14.4], [13.0, 14.16], [14.0, 13.76], [15.0, 13.2], [16.0, 12.48], [17.0, 11.6]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.0, 16.8], [8.0, 17.36], [9.0, 17.76], [10.0, 18.0], [11.0, 18.08], [12.0, 18.0], [13.0, 17.76], [14.0, 17.36], [15.0, 16.8], [16.0, 16.08], [17.0, 15.2]], closed: false, tris: &[] }] },
        ],
        // Combine
        Symbol::Combine => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[9.5, 9.5], [5.17, 7.0], [9.5, 4.5], [13.83, 7.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[9.5, 9.5], [5.17, 7.0], [5.17, 14.0], [9.5, 16.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[9.5, 9.5], [13.83, 7.0], [13.83, 14.0], [9.5, 16.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[9.5, 16.5], [5.17, 14.0], [5.17, 7.0], [9.5, 4.5], [13.83, 7.0], [13.83, 14.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.17, 7.0], [9.5, 9.5], [13.83, 7.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[9.5, 9.5], [9.5, 16.5]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.5, 14.5], [10.17, 12.0], [14.5, 9.5], [18.83, 12.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.5, 14.5], [10.17, 12.0], [10.17, 19.0], [14.5, 21.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[14.5, 14.5], [18.83, 12.0], [18.83, 19.0], [14.5, 21.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.5, 21.5], [10.17, 19.0], [10.17, 12.0], [14.5, 9.5], [18.83, 12.0], [18.83, 19.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[10.17, 12.0], [14.5, 14.5], [18.83, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.5, 14.5], [14.5, 21.5]], closed: false, tris: &[] }] },
        ],
        // Move
        Symbol::Move => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.4], [8.02, 10.1], [12.0, 7.8], [15.98, 10.1]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.4], [8.02, 10.1], [8.02, 14.7], [12.0, 17.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.4], [15.98, 10.1], [15.98, 14.7], [12.0, 17.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 17.0], [8.02, 14.7], [8.02, 10.1], [12.0, 7.8], [15.98, 10.1], [15.98, 14.7]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.02, 10.1], [12.0, 12.4], [15.98, 10.1]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 12.4], [12.0, 17.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 9.2], [12.0, 2.6]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[13.87, 4.8], [12.0, 2.6], [10.13, 4.8]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[7.9, 16.4], [3.4, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.37, 16.28], [3.4, 19.0], [6.24, 19.52]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[16.1, 16.4], [20.6, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[17.76, 19.52], [20.6, 19.0], [19.63, 16.28]], closed: false, tris: &[] }] },
        ],
        // Offset Plane
        Symbol::OffsetPlane => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 17.5], [11.0, 13.5], [19.0, 17.5], [11.0, 21.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 7.5], [11.0, 3.5], [19.0, 7.5], [11.0, 11.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[21.0, 17.5], [21.0, 8.6]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[22.87, 9.8], [21.0, 7.6], [19.13, 9.8]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[21.0, 7.6], [21.0, 8.6]], closed: false, tris: &[] }] },
        ],
        // Plane at Angle
        Symbol::AngledPlane => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.34, 16.0], [11.13, 11.5], [19.79, 16.5], [12.0, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.34, 16.0], [11.13, 11.5], [13.63, 3.0], [5.84, 7.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.34, 16.0], [11.13, 11.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[11.74, 16.35], [12.31, 14.9], [12.42, 13.34], [12.06, 11.82], [11.27, 10.47], [10.12, 9.42], [8.7, 8.76]], closed: false, tris: &[] }] },
        ],
        // New Component
        Symbol::Component => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[10.5, 14.5], [5.3, 11.5], [10.5, 8.5], [15.7, 11.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[10.5, 14.5], [5.3, 11.5], [5.3, 18.0], [10.5, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[10.5, 14.5], [15.7, 11.5], [15.7, 18.0], [10.5, 21.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[10.5, 21.0], [5.3, 18.0], [5.3, 11.5], [10.5, 8.5], [15.7, 11.5], [15.7, 18.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.3, 11.5], [10.5, 14.5], [15.7, 11.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[10.5, 14.5], [10.5, 21.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[18.5, 2.5], [18.5, 9.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[15.0, 6.0], [22.0, 6.0]], closed: false, tris: &[] }] },
        ],
        // Simulate
        Symbol::Simulate => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 4.0], [3.0, 20.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 0.45, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 8.0], [19.0, 8.0], [19.0, 12.0], [3.0, 12.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 12.0], [4.78, 12.05], [6.52, 12.18], [8.22, 12.4], [9.88, 12.72], [11.5, 13.12], [13.08, 13.62], [14.62, 14.21], [16.12, 14.88], [17.58, 15.64], [19.0, 16.5], [18.0, 19.8], [16.59, 19.08], [15.16, 18.43], [13.71, 17.86], [12.24, 17.37], [10.75, 16.95], [9.24, 16.61], [7.71, 16.34], [6.16, 16.15], [4.59, 16.04], [3.0, 16.0]], closed: true, tris: &[[21, 0, 1], [21, 1, 2], [21, 2, 3], [21, 3, 4], [21, 4, 5], [21, 5, 6], [21, 6, 7], [21, 7, 8], [21, 8, 9], [9, 10, 11], [9, 11, 12], [9, 12, 13], [9, 13, 14], [9, 14, 15], [9, 15, 16], [9, 16, 17], [9, 17, 18], [9, 18, 19], [9, 19, 20], [9, 20, 21]] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[21.0, 3.0], [21.0, 11.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[19.08, 9.8], [21.0, 12.2], [22.92, 9.8]], closed: false, tris: &[] }] },
        ],
        // Measure
        Symbol::Measure => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.2, 12.0], [20.51, 12.06], [20.77, 12.23], [20.94, 12.49], [21.0, 12.8], [21.0, 18.7], [20.94, 19.01], [20.77, 19.27], [20.51, 19.44], [20.2, 19.5], [3.8, 19.5], [3.49, 19.44], [3.23, 19.27], [3.06, 19.01], [3.0, 18.7], [3.0, 12.8], [3.06, 12.49], [3.23, 12.23], [3.49, 12.06], [3.8, 12.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[6.5, 12.0], [6.5, 14.5]], closed: false, tris: &[] }, Path { pts: &[[10.0, 12.0], [10.0, 16.0]], closed: false, tris: &[] }, Path { pts: &[[13.5, 12.0], [13.5, 14.5]], closed: false, tris: &[] }, Path { pts: &[[17.0, 12.0], [17.0, 16.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.6, 6.5], [20.4, 6.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.6, 4.63], [3.4, 6.5], [5.6, 8.37]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[18.4, 8.37], [20.6, 6.5], [18.4, 4.63]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 3.8], [3.0, 9.0]], closed: false, tris: &[] }, Path { pts: &[[21.0, 3.8], [21.0, 9.0]], closed: false, tris: &[] }] },
        ],
        // Fit
        Symbol::Fit => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 8.0], [3.0, 3.0], [8.0, 3.0]], closed: false, tris: &[] }, Path { pts: &[[16.0, 3.0], [21.0, 3.0], [21.0, 8.0]], closed: false, tris: &[] }, Path { pts: &[[21.0, 16.0], [21.0, 21.0], [16.0, 21.0]], closed: false, tris: &[] }, Path { pts: &[[8.0, 21.0], [3.0, 21.0], [3.0, 16.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.2], [8.54, 10.2], [12.0, 8.2], [15.46, 10.2]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.2], [8.54, 10.2], [8.54, 14.6], [12.0, 16.6]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 0.55 }), stroke: None, paths: &[Path { pts: &[[12.0, 12.2], [15.46, 10.2], [15.46, 14.6], [12.0, 16.6]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 16.6], [8.54, 14.6], [8.54, 10.2], [12.0, 8.2], [15.46, 10.2], [15.46, 14.6]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.54, 10.2], [12.0, 12.2], [15.46, 10.2]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 12.2], [12.0, 16.6]], closed: false, tris: &[] }] },
        ],
        // Select
        Symbol::Select => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[6.0, 3.5], [6.0, 18.5], [10.0, 14.6], [12.8, 20.6], [15.4, 19.4], [12.6, 13.6], [18.0, 13.4]], closed: true, tris: &[[0, 6, 5], [0, 5, 4], [0, 4, 3], [0, 3, 2], [2, 1, 0]] }] },
        ],
        // Line
        Symbol::Line => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 19.0], [19.0, 5.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[6.6, 19.0], [6.48, 19.61], [6.13, 20.13], [5.61, 20.48], [5.0, 20.6], [4.39, 20.48], [3.87, 20.13], [3.52, 19.61], [3.4, 19.0], [3.52, 18.39], [3.87, 17.87], [4.39, 17.52], [5.0, 17.4], [5.61, 17.52], [6.13, 17.87], [6.48, 18.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[20.6, 5.0], [20.48, 5.61], [20.13, 6.13], [19.61, 6.48], [19.0, 6.6], [18.39, 6.48], [17.87, 6.13], [17.52, 5.61], [17.4, 5.0], [17.52, 4.39], [17.87, 3.87], [18.39, 3.52], [19.0, 3.4], [19.61, 3.52], [20.13, 3.87], [20.48, 4.39]], closed: true, tris: &[] }] },
        ],
        // Rectangle
        Symbol::Rectangle => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[19.4, 6.0], [19.63, 6.05], [19.82, 6.18], [19.95, 6.37], [20.0, 6.6], [20.0, 17.4], [19.95, 17.63], [19.82, 17.82], [19.63, 17.95], [19.4, 18.0], [4.6, 18.0], [4.37, 17.95], [4.18, 17.82], [4.05, 17.63], [4.0, 17.4], [4.0, 6.6], [4.05, 6.37], [4.18, 6.18], [4.37, 6.05], [4.6, 6.0]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.6, 18.0], [5.48, 18.61], [5.13, 19.13], [4.61, 19.48], [4.0, 19.6], [3.39, 19.48], [2.87, 19.13], [2.52, 18.61], [2.4, 18.0], [2.52, 17.39], [2.87, 16.87], [3.39, 16.52], [4.0, 16.4], [4.61, 16.52], [5.13, 16.87], [5.48, 17.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 6.0], [21.48, 6.61], [21.13, 7.13], [20.61, 7.48], [20.0, 7.6], [19.39, 7.48], [18.87, 7.13], [18.52, 6.61], [18.4, 6.0], [18.52, 5.39], [18.87, 4.87], [19.39, 4.52], [20.0, 4.4], [20.61, 4.52], [21.13, 4.87], [21.48, 5.39]], closed: true, tris: &[] }] },
        ],
        // Center Rectangle
        Symbol::CenterRectangle => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[19.4, 6.0], [19.63, 6.05], [19.82, 6.18], [19.95, 6.37], [20.0, 6.6], [20.0, 17.4], [19.95, 17.63], [19.82, 17.82], [19.63, 17.95], [19.4, 18.0], [4.6, 18.0], [4.37, 17.95], [4.18, 17.82], [4.05, 17.63], [4.0, 17.4], [4.0, 6.6], [4.05, 6.37], [4.18, 6.18], [4.37, 6.05], [4.6, 6.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 12.0], [20.0, 6.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 12.0], [13.48, 12.61], [13.13, 13.13], [12.61, 13.48], [12.0, 13.6], [11.39, 13.48], [10.87, 13.13], [10.52, 12.61], [10.4, 12.0], [10.52, 11.39], [10.87, 10.87], [11.39, 10.52], [12.0, 10.4], [12.61, 10.52], [13.13, 10.87], [13.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 6.0], [21.48, 6.61], [21.13, 7.13], [20.61, 7.48], [20.0, 7.6], [19.39, 7.48], [18.87, 7.13], [18.52, 6.61], [18.4, 6.0], [18.52, 5.39], [18.87, 4.87], [19.39, 4.52], [20.0, 4.4], [20.61, 4.52], [21.13, 4.87], [21.48, 5.39]], closed: true, tris: &[] }] },
        ],
        // Circle
        Symbol::Circle => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.0, 12.0], [19.73, 14.07], [18.93, 16.0], [17.66, 17.66], [16.0, 18.93], [14.07, 19.73], [12.0, 20.0], [9.93, 19.73], [8.0, 18.93], [6.34, 17.66], [5.07, 16.0], [4.27, 14.07], [4.0, 12.0], [4.27, 9.93], [5.07, 8.0], [6.34, 6.34], [8.0, 5.07], [9.93, 4.27], [12.0, 4.0], [14.07, 4.27], [16.0, 5.07], [17.66, 6.34], [18.93, 8.0], [19.73, 9.93]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 12.0], [17.66, 6.34]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 12.0], [13.48, 12.61], [13.13, 13.13], [12.61, 13.48], [12.0, 13.6], [11.39, 13.48], [10.87, 13.13], [10.52, 12.61], [10.4, 12.0], [10.52, 11.39], [10.87, 10.87], [11.39, 10.52], [12.0, 10.4], [12.61, 10.52], [13.13, 10.87], [13.48, 11.39]], closed: true, tris: &[] }] },
        ],
        // 2-Point Circle
        Symbol::Circle2Point => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.0, 12.0], [19.73, 14.07], [18.93, 16.0], [17.66, 17.66], [16.0, 18.93], [14.07, 19.73], [12.0, 20.0], [9.93, 19.73], [8.0, 18.93], [6.34, 17.66], [5.07, 16.0], [4.27, 14.07], [4.0, 12.0], [4.27, 9.93], [5.07, 8.0], [6.34, 6.34], [8.0, 5.07], [9.93, 4.27], [12.0, 4.0], [14.07, 4.27], [16.0, 5.07], [17.66, 6.34], [18.93, 8.0], [19.73, 9.93]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[4.0, 12.0], [20.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.6, 12.0], [5.48, 12.61], [5.13, 13.13], [4.61, 13.48], [4.0, 13.6], [3.39, 13.48], [2.87, 13.13], [2.52, 12.61], [2.4, 12.0], [2.52, 11.39], [2.87, 10.87], [3.39, 10.52], [4.0, 10.4], [4.61, 10.52], [5.13, 10.87], [5.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 12.0], [21.48, 12.61], [21.13, 13.13], [20.61, 13.48], [20.0, 13.6], [19.39, 13.48], [18.87, 13.13], [18.52, 12.61], [18.4, 12.0], [18.52, 11.39], [18.87, 10.87], [19.39, 10.52], [20.0, 10.4], [20.61, 10.52], [21.13, 10.87], [21.48, 11.39]], closed: true, tris: &[] }] },
        ],
        // 3-Point Circle
        Symbol::Circle3Point => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.0, 12.0], [19.73, 14.07], [18.93, 16.0], [17.66, 17.66], [16.0, 18.93], [14.07, 19.73], [12.0, 20.0], [9.93, 19.73], [8.0, 18.93], [6.34, 17.66], [5.07, 16.0], [4.27, 14.07], [4.0, 12.0], [4.27, 9.93], [5.07, 8.0], [6.34, 6.34], [8.0, 5.07], [9.93, 4.27], [12.0, 4.0], [14.07, 4.27], [16.0, 5.07], [17.66, 6.34], [18.93, 8.0], [19.73, 9.93]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[6.3, 8.5], [6.18, 9.11], [5.83, 9.63], [5.31, 9.98], [4.7, 10.1], [4.09, 9.98], [3.57, 9.63], [3.22, 9.11], [3.1, 8.5], [3.22, 7.89], [3.57, 7.37], [4.09, 7.02], [4.7, 6.9], [5.31, 7.02], [5.83, 7.37], [6.18, 7.89]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[20.9, 8.5], [20.78, 9.11], [20.43, 9.63], [19.91, 9.98], [19.3, 10.1], [18.69, 9.98], [18.17, 9.63], [17.82, 9.11], [17.7, 8.5], [17.82, 7.89], [18.17, 7.37], [18.69, 7.02], [19.3, 6.9], [19.91, 7.02], [20.43, 7.37], [20.78, 7.89]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 20.0], [13.48, 20.61], [13.13, 21.13], [12.61, 21.48], [12.0, 21.6], [11.39, 21.48], [10.87, 21.13], [10.52, 20.61], [10.4, 20.0], [10.52, 19.39], [10.87, 18.87], [11.39, 18.52], [12.0, 18.4], [12.61, 18.52], [13.13, 18.87], [13.48, 19.39]], closed: true, tris: &[] }] },
        ],
        // 3-Point Arc
        Symbol::Arc3Point => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.0, 17.0], [5.41, 14.99], [7.32, 13.44], [9.57, 12.46], [12.0, 12.12], [14.43, 12.46], [16.68, 13.44], [18.59, 14.99], [20.0, 17.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.6, 17.0], [5.48, 17.61], [5.13, 18.13], [4.61, 18.48], [4.0, 18.6], [3.39, 18.48], [2.87, 18.13], [2.52, 17.61], [2.4, 17.0], [2.52, 16.39], [2.87, 15.87], [3.39, 15.52], [4.0, 15.4], [4.61, 15.52], [5.13, 15.87], [5.48, 16.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 17.0], [21.48, 17.61], [21.13, 18.13], [20.61, 18.48], [20.0, 18.6], [19.39, 18.48], [18.87, 18.13], [18.52, 17.61], [18.4, 17.0], [18.52, 16.39], [18.87, 15.87], [19.39, 15.52], [20.0, 15.4], [20.61, 15.52], [21.13, 15.87], [21.48, 16.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 7.45], [13.48, 8.06], [13.13, 8.58], [12.61, 8.93], [12.0, 9.05], [11.39, 8.93], [10.87, 8.58], [10.52, 8.06], [10.4, 7.45], [10.52, 6.84], [10.87, 6.32], [11.39, 5.97], [12.0, 5.85], [12.61, 5.97], [13.13, 6.32], [13.48, 6.84]], closed: true, tris: &[] }] },
        ],
        // Center Arc
        Symbol::ArcCenter => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[20.0, 17.0], [21.38, 14.99], [22.14, 12.67], [22.21, 10.24], [21.59, 7.88], [20.34, 5.79], [18.54, 4.14], [16.36, 3.06], [13.96, 2.64], [11.54, 2.91], [9.29, 3.86], [7.4, 5.4]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 17.0], [20.0, 17.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 17.0], [7.4, 5.4]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 17.0], [13.48, 17.61], [13.13, 18.13], [12.61, 18.48], [12.0, 18.6], [11.39, 18.48], [10.87, 18.13], [10.52, 17.61], [10.4, 17.0], [10.52, 16.39], [10.87, 15.87], [11.39, 15.52], [12.0, 15.4], [12.61, 15.52], [13.13, 15.87], [13.48, 16.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 17.0], [21.48, 17.61], [21.13, 18.13], [20.61, 18.48], [20.0, 18.6], [19.39, 18.48], [18.87, 18.13], [18.52, 17.61], [18.4, 17.0], [18.52, 16.39], [18.87, 15.87], [19.39, 15.52], [20.0, 15.4], [20.61, 15.52], [21.13, 15.87], [21.48, 16.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[9.0, 5.4], [8.88, 6.01], [8.53, 6.53], [8.01, 6.88], [7.4, 7.0], [6.79, 6.88], [6.27, 6.53], [5.92, 6.01], [5.8, 5.4], [5.92, 4.79], [6.27, 4.27], [6.79, 3.92], [7.4, 3.8], [8.01, 3.92], [8.53, 4.27], [8.88, 4.79]], closed: true, tris: &[] }] },
        ],
        // Polygon
        Symbol::Polygon => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 3.5], [19.36, 7.75], [19.36, 16.25], [12.0, 20.5], [4.64, 16.25], [4.64, 7.75]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 12.0], [19.36, 7.75]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 12.0], [13.48, 12.61], [13.13, 13.13], [12.61, 13.48], [12.0, 13.6], [11.39, 13.48], [10.87, 13.13], [10.52, 12.61], [10.4, 12.0], [10.52, 11.39], [10.87, 10.87], [11.39, 10.52], [12.0, 10.4], [12.61, 10.52], [13.13, 10.87], [13.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[20.96, 7.75], [20.84, 8.36], [20.49, 8.88], [19.97, 9.23], [19.36, 9.35], [18.75, 9.23], [18.23, 8.88], [17.88, 8.36], [17.76, 7.75], [17.88, 7.14], [18.23, 6.62], [18.75, 6.27], [19.36, 6.15], [19.97, 6.27], [20.49, 6.62], [20.84, 7.14]], closed: true, tris: &[] }] },
        ],
        // Slot
        Symbol::Slot => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.5, 7.5], [15.5, 7.5], [16.66, 7.65], [17.75, 8.1], [18.68, 8.82], [19.4, 9.75], [19.85, 10.84], [20.0, 12.0], [19.85, 13.16], [19.4, 14.25], [18.68, 15.18], [17.75, 15.9], [16.66, 16.35], [15.5, 16.5], [8.5, 16.5], [7.34, 16.35], [6.25, 15.9], [5.32, 15.18], [4.6, 14.25], [4.15, 13.16], [4.0, 12.0], [4.15, 10.84], [4.6, 9.75], [5.32, 8.82], [6.25, 8.1], [7.34, 7.65]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[8.5, 12.0], [15.5, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[10.1, 12.0], [9.98, 12.61], [9.63, 13.13], [9.11, 13.48], [8.5, 13.6], [7.89, 13.48], [7.37, 13.13], [7.02, 12.61], [6.9, 12.0], [7.02, 11.39], [7.37, 10.87], [7.89, 10.52], [8.5, 10.4], [9.11, 10.52], [9.63, 10.87], [9.98, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[17.1, 12.0], [16.98, 12.61], [16.63, 13.13], [16.11, 13.48], [15.5, 13.6], [14.89, 13.48], [14.37, 13.13], [14.02, 12.61], [13.9, 12.0], [14.02, 11.39], [14.37, 10.87], [14.89, 10.52], [15.5, 10.4], [16.11, 10.52], [16.63, 10.87], [16.98, 11.39]], closed: true, tris: &[] }] },
        ],
        // Overall Slot
        Symbol::SlotOverall => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.5, 7.5], [15.5, 7.5], [16.66, 7.65], [17.75, 8.1], [18.68, 8.82], [19.4, 9.75], [19.85, 10.84], [20.0, 12.0], [19.85, 13.16], [19.4, 14.25], [18.68, 15.18], [17.75, 15.9], [16.66, 16.35], [15.5, 16.5], [8.5, 16.5], [7.34, 16.35], [6.25, 15.9], [5.32, 15.18], [4.6, 14.25], [4.15, 13.16], [4.0, 12.0], [4.15, 10.84], [4.6, 9.75], [5.32, 8.82], [6.25, 8.1], [7.34, 7.65]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[4.0, 12.0], [20.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.6, 12.0], [5.48, 12.61], [5.13, 13.13], [4.61, 13.48], [4.0, 13.6], [3.39, 13.48], [2.87, 13.13], [2.52, 12.61], [2.4, 12.0], [2.52, 11.39], [2.87, 10.87], [3.39, 10.52], [4.0, 10.4], [4.61, 10.52], [5.13, 10.87], [5.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 12.0], [21.48, 12.61], [21.13, 13.13], [20.61, 13.48], [20.0, 13.6], [19.39, 13.48], [18.87, 13.13], [18.52, 12.61], [18.4, 12.0], [18.52, 11.39], [18.87, 10.87], [19.39, 10.52], [20.0, 10.4], [20.61, 10.52], [21.13, 10.87], [21.48, 11.39]], closed: true, tris: &[] }] },
        ],
        // Center Point Slot
        Symbol::SlotCenterPoint => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.5, 7.5], [15.5, 7.5], [16.66, 7.65], [17.75, 8.1], [18.68, 8.82], [19.4, 9.75], [19.85, 10.84], [20.0, 12.0], [19.85, 13.16], [19.4, 14.25], [18.68, 15.18], [17.75, 15.9], [16.66, 16.35], [15.5, 16.5], [8.5, 16.5], [7.34, 16.35], [6.25, 15.9], [5.32, 15.18], [4.6, 14.25], [4.15, 13.16], [4.0, 12.0], [4.15, 10.84], [4.6, 9.75], [5.32, 8.82], [6.25, 8.1], [7.34, 7.65]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[12.0, 12.0], [15.5, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 12.0], [13.48, 12.61], [13.13, 13.13], [12.61, 13.48], [12.0, 13.6], [11.39, 13.48], [10.87, 13.13], [10.52, 12.61], [10.4, 12.0], [10.52, 11.39], [10.87, 10.87], [11.39, 10.52], [12.0, 10.4], [12.61, 10.52], [13.13, 10.87], [13.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[17.1, 12.0], [16.98, 12.61], [16.63, 13.13], [16.11, 13.48], [15.5, 13.6], [14.89, 13.48], [14.37, 13.13], [14.02, 12.61], [13.9, 12.0], [14.02, 11.39], [14.37, 10.87], [14.89, 10.52], [15.5, 10.4], [16.11, 10.52], [16.63, 10.87], [16.98, 11.39]], closed: true, tris: &[] }] },
        ],
        // Text
        Symbol::Text => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 4.5], [19.0, 4.5]], closed: false, tris: &[] }, Path { pts: &[[12.0, 4.5], [12.0, 19.5]], closed: false, tris: &[] }, Path { pts: &[[9.0, 19.5], [15.0, 19.5]], closed: false, tris: &[] }, Path { pts: &[[5.0, 4.5], [5.0, 7.0]], closed: false, tris: &[] }, Path { pts: &[[19.0, 4.5], [19.0, 7.0]], closed: false, tris: &[] }] },
        ],
        // Dimension
        Symbol::Dimension => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 6.0], [5.0, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[19.0, 6.0], [19.0, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.8, 10.5], [18.2, 10.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.2, 8.46], [5.8, 10.5], [8.2, 12.54]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[15.8, 12.54], [18.2, 10.5], [15.8, 8.46]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 0.45, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 19.0], [19.0, 19.0]], closed: false, tris: &[] }] },
        ],
        // Trim
        Symbol::Trim => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[8.0, 4.0], [8.0, 20.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[16.0, 4.0], [16.0, 20.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[3.0, 12.0], [8.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[16.0, 12.0], [21.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[10.0, 12.0], [14.0, 12.0]], closed: false, tris: &[] }] },
        ],
        // Break
        Symbol::Break => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.0, 19.0], [10.4, 13.2]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[13.6, 10.8], [20.0, 5.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 12.0], [13.48, 12.61], [13.13, 13.13], [12.61, 13.48], [12.0, 13.6], [11.39, 13.48], [10.87, 13.13], [10.52, 12.61], [10.4, 12.0], [10.52, 11.39], [10.87, 10.87], [11.39, 10.52], [12.0, 10.4], [12.61, 10.52], [13.13, 10.87], [13.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 0.45, width: 1.5, dash: None }), paths: &[Path { pts: &[[9.0, 9.0], [15.0, 15.0]], closed: false, tris: &[] }] },
        ],
        // Sketch Fillet
        Symbol::SketchFillet => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 0.55, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[5.0, 12.0], [5.0, 5.0], [12.0, 5.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 20.0], [5.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 5.0], [20.0, 5.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.0, 12.0], [5.24, 10.19], [5.94, 8.5], [7.05, 7.05], [8.5, 5.94], [10.19, 5.24], [12.0, 5.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[6.6, 12.0], [6.48, 12.61], [6.13, 13.13], [5.61, 13.48], [5.0, 13.6], [4.39, 13.48], [3.87, 13.13], [3.52, 12.61], [3.4, 12.0], [3.52, 11.39], [3.87, 10.87], [4.39, 10.52], [5.0, 10.4], [5.61, 10.52], [6.13, 10.87], [6.48, 11.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.6, 5.0], [13.48, 5.61], [13.13, 6.13], [12.61, 6.48], [12.0, 6.6], [11.39, 6.48], [10.87, 6.13], [10.52, 5.61], [10.4, 5.0], [10.52, 4.39], [10.87, 3.87], [11.39, 3.52], [12.0, 3.4], [12.61, 3.52], [13.13, 3.87], [13.48, 4.39]], closed: true, tris: &[] }] },
        ],
        // Construction
        Symbol::Construction => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[4.0, 20.0], [20.0, 4.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[17.0, 12.0], [16.83, 13.29], [16.33, 14.5], [15.54, 15.54], [14.5, 16.33], [13.29, 16.83], [12.0, 17.0], [10.71, 16.83], [9.5, 16.33], [8.46, 15.54], [7.67, 14.5], [7.17, 13.29], [7.0, 12.0], [7.17, 10.71], [7.67, 9.5], [8.46, 8.46], [9.5, 7.67], [10.71, 7.17], [12.0, 7.0], [13.29, 7.17], [14.5, 7.67], [15.54, 8.46], [16.33, 9.5], [16.83, 10.71]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.6, 20.0], [5.48, 20.61], [5.13, 21.13], [4.61, 21.48], [4.0, 21.6], [3.39, 21.48], [2.87, 21.13], [2.52, 20.61], [2.4, 20.0], [2.52, 19.39], [2.87, 18.87], [3.39, 18.52], [4.0, 18.4], [4.61, 18.52], [5.13, 18.87], [5.48, 19.39]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[21.6, 4.0], [21.48, 4.61], [21.13, 5.13], [20.61, 5.48], [20.0, 5.6], [19.39, 5.48], [18.87, 5.13], [18.52, 4.61], [18.4, 4.0], [18.52, 3.39], [18.87, 2.87], [19.39, 2.52], [20.0, 2.4], [20.61, 2.52], [21.13, 2.87], [21.48, 3.39]], closed: true, tris: &[] }] },
        ],
        // Delete
        Symbol::Delete => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[4.5, 6.5], [19.5, 6.5]], closed: false, tris: &[] }, Path { pts: &[[9.5, 6.5], [9.5, 4.0], [14.5, 4.0], [14.5, 6.5]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[6.5, 6.5], [7.5, 20.0], [16.5, 20.0], [17.5, 6.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[10.3, 10.0], [10.3, 16.5]], closed: false, tris: &[] }, Path { pts: &[[13.7, 10.0], [13.7, 16.5]], closed: false, tris: &[] }] },
        ],
        // Sketch Move
        Symbol::SketchMove => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[12.0, 3.0], [12.0, 21.0]], closed: false, tris: &[] }, Path { pts: &[[3.0, 12.0], [21.0, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.04, 5.4], [12.0, 3.0], [9.96, 5.4]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[9.96, 18.6], [12.0, 21.0], [14.04, 18.6]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[5.4, 9.96], [3.0, 12.0], [5.4, 14.04]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[18.6, 14.04], [21.0, 12.0], [18.6, 9.96]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Accent, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.0, 12.0], [13.85, 12.77], [13.41, 13.41], [12.77, 13.85], [12.0, 14.0], [11.23, 13.85], [10.59, 13.41], [10.15, 12.77], [10.0, 12.0], [10.15, 11.23], [10.59, 10.59], [11.23, 10.15], [12.0, 10.0], [12.77, 10.15], [13.41, 10.59], [13.85, 11.23]], closed: true, tris: &[] }] },
        ],
        // Pattern
        Symbol::Pattern => &[
            Prim { fill: Some(Paint { ink: Ink::Faint, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[9.0, 3.5], [9.38, 3.58], [9.71, 3.79], [9.92, 4.12], [10.0, 4.5], [10.0, 9.0], [9.92, 9.38], [9.71, 9.71], [9.38, 9.92], [9.0, 10.0], [4.5, 10.0], [4.12, 9.92], [3.79, 9.71], [3.58, 9.38], [3.5, 9.0], [3.5, 4.5], [3.58, 4.12], [3.79, 3.79], [4.12, 3.58], [4.5, 3.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[19.5, 3.5], [19.88, 3.58], [20.21, 3.79], [20.42, 4.12], [20.5, 4.5], [20.5, 9.0], [20.42, 9.38], [20.21, 9.71], [19.88, 9.92], [19.5, 10.0], [15.0, 10.0], [14.62, 9.92], [14.29, 9.71], [14.08, 9.38], [14.0, 9.0], [14.0, 4.5], [14.08, 4.12], [14.29, 3.79], [14.62, 3.58], [15.0, 3.5]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[9.0, 14.0], [9.38, 14.08], [9.71, 14.29], [9.92, 14.62], [10.0, 15.0], [10.0, 19.5], [9.92, 19.88], [9.71, 20.21], [9.38, 20.42], [9.0, 20.5], [4.5, 20.5], [4.12, 20.42], [3.79, 20.21], [3.58, 19.88], [3.5, 19.5], [3.5, 15.0], [3.58, 14.62], [3.79, 14.29], [4.12, 14.08], [4.5, 14.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: Some([2.0, 2.2]) }), paths: &[Path { pts: &[[19.5, 14.0], [19.88, 14.08], [20.21, 14.29], [20.42, 14.62], [20.5, 15.0], [20.5, 19.5], [20.42, 19.88], [20.21, 20.21], [19.88, 20.42], [19.5, 20.5], [15.0, 20.5], [14.62, 20.42], [14.29, 20.21], [14.08, 19.88], [14.0, 19.5], [14.0, 15.0], [14.08, 14.62], [14.29, 14.29], [14.62, 14.08], [15.0, 14.0]], closed: true, tris: &[] }] },
        ],
        // Offset
        Symbol::Offset => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.8, 8.0], [15.26, 8.09], [15.65, 8.35], [15.91, 8.74], [16.0, 9.2], [16.0, 14.8], [15.91, 15.26], [15.65, 15.65], [15.26, 15.91], [14.8, 16.0], [9.2, 16.0], [8.74, 15.91], [8.35, 15.65], [8.09, 15.26], [8.0, 14.8], [8.0, 9.2], [8.09, 8.74], [8.35, 8.35], [8.74, 8.09], [9.2, 8.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 1.5, dash: None }), paths: &[Path { pts: &[[14.8, 3.5], [16.98, 3.93], [18.83, 5.17], [20.07, 7.02], [20.5, 9.2], [20.5, 14.8], [20.07, 16.98], [18.83, 18.83], [16.98, 20.07], [14.8, 20.5], [9.2, 20.5], [7.02, 20.07], [5.17, 18.83], [3.93, 16.98], [3.5, 14.8], [3.5, 9.2], [3.93, 7.02], [5.17, 5.17], [7.02, 3.93], [9.2, 3.5]], closed: true, tris: &[] }] },
        ],
        // Finish Sketch
        Symbol::FinishSketch => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Accent, alpha: 1.0, width: 2.2, dash: None }), paths: &[Path { pts: &[[4.5, 12.5], [9.8, 17.8], [19.5, 6.5]], closed: false, tris: &[] }] },
        ],
        // Coincident
        Symbol::Coincident => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[4.0, 19.0], [12.0, 7.5]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 7.5], [20.0, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.8, 7.5], [14.7, 8.22], [14.42, 8.9], [13.98, 9.48], [13.4, 9.92], [12.72, 10.2], [12.0, 10.3], [11.28, 10.2], [10.6, 9.92], [10.02, 9.48], [9.58, 8.9], [9.3, 8.22], [9.2, 7.5], [9.3, 6.78], [9.58, 6.1], [10.02, 5.52], [10.6, 5.08], [11.28, 4.8], [12.0, 4.7], [12.72, 4.8], [13.4, 5.08], [13.98, 5.52], [14.42, 6.1], [14.7, 6.78]], closed: true, tris: &[] }] },
        ],
        // Horizontal
        Symbol::Horizontal => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[3.5, 12.0], [20.5, 12.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[5.7, 12.0], [5.53, 12.84], [5.06, 13.56], [4.34, 14.03], [3.5, 14.2], [2.66, 14.03], [1.94, 13.56], [1.47, 12.84], [1.3, 12.0], [1.47, 11.16], [1.94, 10.44], [2.66, 9.97], [3.5, 9.8], [4.34, 9.97], [5.06, 10.44], [5.53, 11.16]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[22.7, 12.0], [22.53, 12.84], [22.06, 13.56], [21.34, 14.03], [20.5, 14.2], [19.66, 14.03], [18.94, 13.56], [18.47, 12.84], [18.3, 12.0], [18.47, 11.16], [18.94, 10.44], [19.66, 9.97], [20.5, 9.8], [21.34, 9.97], [22.06, 10.44], [22.53, 11.16]], closed: true, tris: &[] }] },
        ],
        // Vertical
        Symbol::Vertical => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 3.5], [12.0, 20.5]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.2, 3.5], [14.03, 4.34], [13.56, 5.06], [12.84, 5.53], [12.0, 5.7], [11.16, 5.53], [10.44, 5.06], [9.97, 4.34], [9.8, 3.5], [9.97, 2.66], [10.44, 1.94], [11.16, 1.47], [12.0, 1.3], [12.84, 1.47], [13.56, 1.94], [14.03, 2.66]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.2, 20.5], [14.03, 21.34], [13.56, 22.06], [12.84, 22.53], [12.0, 22.7], [11.16, 22.53], [10.44, 22.06], [9.97, 21.34], [9.8, 20.5], [9.97, 19.66], [10.44, 18.94], [11.16, 18.47], [12.0, 18.3], [12.84, 18.47], [13.56, 18.94], [14.03, 19.66]], closed: true, tris: &[] }] },
        ],
        // Parallel
        Symbol::Parallel => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[5.0, 20.0], [12.0, 4.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 20.0], [19.0, 4.0]], closed: false, tris: &[] }] },
        ],
        // Perpendicular
        Symbol::Perpendicular => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[4.0, 20.0], [20.0, 20.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 20.0], [12.0, 4.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 15.5], [16.5, 15.5], [16.5, 20.0]], closed: false, tris: &[] }] },
        ],
        // Tangent
        Symbol::Tangent => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[18.0, 14.0], [17.8, 15.55], [17.2, 17.0], [16.24, 18.24], [15.0, 19.2], [13.55, 19.8], [12.0, 20.0], [10.45, 19.8], [9.0, 19.2], [7.76, 18.24], [6.8, 17.0], [6.2, 15.55], [6.0, 14.0], [6.2, 12.45], [6.8, 11.0], [7.76, 9.76], [9.0, 8.8], [10.45, 8.2], [12.0, 8.0], [13.55, 8.2], [15.0, 8.8], [16.24, 9.76], [17.2, 11.0], [17.8, 12.45]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[3.0, 8.0], [21.0, 8.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[14.2, 8.0], [14.03, 8.84], [13.56, 9.56], [12.84, 10.03], [12.0, 10.2], [11.16, 10.03], [10.44, 9.56], [9.97, 8.84], [9.8, 8.0], [9.97, 7.16], [10.44, 6.44], [11.16, 5.97], [12.0, 5.8], [12.84, 5.97], [13.56, 6.44], [14.03, 7.16]], closed: true, tris: &[] }] },
        ],
        // Equal
        Symbol::Equal => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[5.0, 9.0], [19.0, 9.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[5.0, 15.0], [19.0, 15.0]], closed: false, tris: &[] }] },
        ],
        // Concentric
        Symbol::Concentric => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[20.5, 12.0], [20.21, 14.2], [19.36, 16.25], [18.01, 18.01], [16.25, 19.36], [14.2, 20.21], [12.0, 20.5], [9.8, 20.21], [7.75, 19.36], [5.99, 18.01], [4.64, 16.25], [3.79, 14.2], [3.5, 12.0], [3.79, 9.8], [4.64, 7.75], [5.99, 5.99], [7.75, 4.64], [9.8, 3.79], [12.0, 3.5], [14.2, 3.79], [16.25, 4.64], [18.01, 5.99], [19.36, 7.75], [20.21, 9.8]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[16.0, 12.0], [15.86, 13.04], [15.46, 14.0], [14.83, 14.83], [14.0, 15.46], [13.04, 15.86], [12.0, 16.0], [10.96, 15.86], [10.0, 15.46], [9.17, 14.83], [8.54, 14.0], [8.14, 13.04], [8.0, 12.0], [8.14, 10.96], [8.54, 10.0], [9.17, 9.17], [10.0, 8.54], [10.96, 8.14], [12.0, 8.0], [13.04, 8.14], [14.0, 8.54], [14.83, 9.17], [15.46, 10.0], [15.86, 10.96]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: None, paths: &[Path { pts: &[[13.4, 12.0], [13.29, 12.54], [12.99, 12.99], [12.54, 13.29], [12.0, 13.4], [11.46, 13.29], [11.01, 12.99], [10.71, 12.54], [10.6, 12.0], [10.71, 11.46], [11.01, 11.01], [11.46, 10.71], [12.0, 10.6], [12.54, 10.71], [12.99, 11.01], [13.29, 11.46]], closed: true, tris: &[] }] },
        ],
        // Midpoint
        Symbol::Midpoint => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[3.5, 16.0], [20.5, 16.0]], closed: false, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[3.5, 13.0], [3.5, 19.0]], closed: false, tris: &[] }, Path { pts: &[[20.5, 13.0], [20.5, 19.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[12.0, 9.5], [15.0, 14.5], [9.0, 14.5]], closed: true, tris: &[] }] },
        ],
        // Symmetric
        Symbol::Symmetric => &[
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: Some([2.5, 2.5]) }), paths: &[Path { pts: &[[12.0, 3.0], [12.0, 21.0]], closed: false, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[3.5, 7.5], [9.0, 12.0], [3.5, 16.5]], closed: true, tris: &[] }] },
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[20.5, 7.5], [15.0, 12.0], [20.5, 16.5]], closed: true, tris: &[] }] },
        ],
        // Fix
        Symbol::Fix => &[
            Prim { fill: Some(Paint { ink: Ink::Main, alpha: 1.0 }), stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[17.0, 11.0], [17.57, 11.11], [18.06, 11.44], [18.39, 11.93], [18.5, 12.5], [18.5, 19.0], [18.39, 19.57], [18.06, 20.06], [17.57, 20.39], [17.0, 20.5], [7.0, 20.5], [6.43, 20.39], [5.94, 20.06], [5.61, 19.57], [5.5, 19.0], [5.5, 12.5], [5.61, 11.93], [5.94, 11.44], [6.43, 11.11], [7.0, 11.0]], closed: true, tris: &[] }] },
            Prim { fill: None, stroke: Some(Pen { ink: Ink::Main, alpha: 1.0, width: 2.0, dash: None }), paths: &[Path { pts: &[[8.5, 11.0], [8.5, 8.0], [8.62, 7.09], [8.97, 6.25], [9.53, 5.53], [10.25, 4.97], [11.09, 4.62], [12.0, 4.5], [12.91, 4.62], [13.75, 4.97], [14.47, 5.53], [15.03, 6.25], [15.38, 7.09], [15.5, 8.0], [15.5, 11.0]], closed: false, tris: &[] }] },
        ],
    }
}
